#pragma once
// Use folowing define to use legacy coordinate system (0,0) is bottom left, y+ up, x+ right. Otherwise (0,0) is top left, y+ down, x+ right.
// #define LEGACY_COORDINATE_SYSTEM
#include "sdl2_misc.h"
#include "basicui.h"
#include "camera.h"
#include "camera3d.h"
#include "FastCont.h"
#include "keyboard.h"
#include "mouse.h"
#include "controller.h"
#include "netagent.h"
#include "particles.h"
#include "shapes.h"
#include "smooth.h"
#include "sprite.h"
#include "timer.h"
#include "profiler.h"
#include "audio/audio.h"
#include "audio/speech_sinthesys.h"
